[package]
name = "systems"
version = "0.1.0"
authors = ["Zoee Silcock <mrzoee@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
iyes_perf_ui = "0.2.3"
rand = "0.8.5"
components = { path = "../components" }
