[package]
name = "systems"
version = "0.1.0"
authors = ["Zoee Silcock <mrzoee@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
bevy = "0.13.2"
iyes_perf_ui = "0.2.3"
rand = "0.8.5"
components = { path = "../components" }

[features]
default = []
dynamic = ["bevy/dynamic_linking"]
